const fs = require('node:fs');
const path = require('node:path');
const { test, expect } = require('@playwright/test');
const { getContext, loginViaUi, createApiSession } = require('./helpers');

test('admin can read live logs, pause, filter and download on desktop and mobile', async ({ page }, testInfo) => {
  const context = getContext();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await loginViaUi(page, context.adminUser);
  await page.locator('#settingsBtn').click();
  await page.locator('#settingsAdminPanel').click();
  await page.locator('#adminLogsOpenBtn').click();
  await expect(page.locator('#adminLogsModal')).toBeVisible();
  await expect(page.locator('#adminLogsConnection')).toHaveText('Подключено');
  const session = createApiSession();
  await session.login(context.adminUser);
  const marker = '/api/logs-browser-check-' + Date.now();
  const started = Date.now();
  await session.request(marker, { expectedStatus: 404 });
  await expect(page.locator('#adminLogsEntries')).toContainText(marker, { timeout: 1000 });
  expect(Date.now() - started).toBeLessThan(1000);
  expect(fs.readFileSync(path.join(context.appDir, 'logs/bananza.log'), 'utf8')).toContain(marker);
  await page.locator('#adminLogsLevel').selectOption('warn');
  await page.locator('#adminLogsSearch').fill(marker);
  await expect(page.locator('#adminLogsEntries .admin-log-entry')).toHaveCount(1);
  await page.locator('#adminLogsPause').click();
  await expect(page.locator('#adminLogsPause')).toHaveText('Продолжить показ');
  const secondMarker = marker + '-paused';
  await session.request(secondMarker, { expectedStatus: 404 });
  await page.waitForTimeout(250);
  await expect(page.locator('#adminLogsEntries')).not.toContainText(secondMarker);
  await page.locator('#adminLogsPause').click();
  await expect(page.locator('#adminLogsEntries')).toContainText(secondMarker);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#adminLogsDownload').click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('bananza.log');
  expect(fs.readFileSync(await download.path(), 'utf8')).toContain(marker);
  const bounds = await page.locator('#adminLogsModal .modal-content').boundingBox();
  expect(bounds.width).toBeLessThanOrEqual(page.viewportSize().width);
  await page.screenshot({ path: testInfo.outputPath('admin-logs.png') });
  await page.locator('#adminLogsModal .modal-close').click();
  await expect(page.locator('#adminLogsModal')).toBeHidden();
  await expect(page.locator('#adminLogsEntries')).toBeEmpty();
  expect(errors).toEqual([]);
});
